name: SonarCloud Scan (Java simple)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour une analyse complète

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Étape optionnelle : compiler ton code si besoin
      - name: Compile Java (optional)
        run: |
          mkdir -p bin
          javac -d bin $(find src -name "*.java")

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=souaibou18
            -Dsonar.projectKey=souaibou18_sonarqube-test
            -Dsonar.host.url=https://sonarcloud.io
