name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Get modified files
        id: gitdiff
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.java$' | tr '\n' ',')
          echo "Modified files: $FILES"
          echo "files=$FILES" >> $GITHUB_OUTPUT    

      - name: Run SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt   
          
      - name: Comment PR with SonarCloud summary
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :bar_chart: SonarCloud Analysis Summary
            - **Quality Gate:** ${{ steps.qg.outputs.qualityGateStatus }}
            - **Branch:** ${{ github.head_ref }}
            - **Project Key:** souaibou18_sonarqube-test
            - Check details: [SonarCloud project](https://sonarcloud.io/project/issues?id=souaibou18_sonarqube-test&pullRequest=${{ github.event.pull_request.number }})
